name: MultiGenerator
version: '${project.version}-${git.commit.id.abbrev}'
author: RoboMWM
main: com.robomwm.multigenerator.MultiGenerator
api-version: '1.16'
load: STARTUP
softdepend:
  - CityWorld
  - WellWorld
  - MaxiWorld
  - DungeonMaze
loadbefore:
  - Multiverse-Core
commands:
  getChunkAt:
    usage: /getChunkAt <world> <x> <z>
    permission: MultiGenerator.getChunkAt
permissions:
  MultiGenerator.getChunkAt:
    default: op

